import { SkillGroup } from "@/types";

export const skillGroups: SkillGroup[] = [
  {
    category: "Machine Learning & Deep Learning",
    skills: [
      "PyTorch",
      "TensorFlow",
      "Keras",
      "Scikit-learn",
      "HuggingFace Transformers",
      "LoRA / QLoRA / PEFT",
      "XGBoost",
      "LightGBM",
      "Fine-tuning",
      "Transfer Learning",
    ],
  },
  {
    category: "Computer Vision & Medical Imaging",
    skills: [
      "YOLOv8",
      "TransU-Net",
      "U-Net",
      "ViT",
      "SAM",
      "ResNet",
      "DenseNet",
      "BioViL-T",
      "GradCAM",
      "CBAM",
      "OpenCV",
    ],
  },
  {
    category: "Generative Models",
    skills: [
      "GANs",
      "VAEs",
      "Diffusion Models",
      "Flow Matching",
      "Knowledge Distillation",
      "Mamba (SSM)",
    ],
  },
  {
    category: "NLP, LLMs & RAG",
    skills: [
      "BERT",
      "LangChain",
      "LangGraph",
      "LlamaIndex",
      "RAG Pipelines",
      "FAISS",
      "Pinecone",
      "Prompt Engineering",
      "OpenAI API",
      "Gemini API",
      "Anthropic API",
    ],
  },
  {
    category: "MLOps & Deployment",
    skills: [
      "MLflow",
      "Docker",
      "Kubernetes",
      "Kubeflow",
      "Prometheus",
      "Grafana",
      "Evidently AI",
      "FastAPI",
      "CI/CD",
      "GitHub Actions",
      "AWS EC2",
      "Vast.ai",
    ],
  },
  {
    category: "Data & Languages",
    skills: [
      "Python",
      "C++",
      "JavaScript",
      "TypeScript",
      "SQL",
      "Pandas",
      "NumPy",
      "PostgreSQL",
      "MongoDB",
      "Git",
    ],
  },
  {
    category: "Frontend & Tools",
    skills: ["React", "Next.js", "Vite", "Power BI", "Nginx"],
  },
];
